# Generated by Django 3.2.19 on 2023-06-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessingImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Image name')),
                ('sourceFile', models.FileField(max_length=254, upload_to='', verbose_name='Source Image File')),
                ('outputFile', models.FileField(max_length=254, upload_to='', verbose_name='Output Image File')),
            ],
        ),
    ]
