# Generated by Django 3.2.19 on 2023-06-03 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralSR_App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingimage',
            name='outputFile',
        ),
    ]
