# Generated by Django 3.2.19 on 2023-06-03 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralSR_App', '0002_remove_processingimage_outputfile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processingimage',
            name='name',
        ),
    ]
