# Generated by Django 3.2.19 on 2023-06-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralSR_App', '0003_remove_processingimage_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='processingimage',
            name='sourceFile',
            field=models.ImageField(upload_to='resources/'),
        ),
    ]
