# Generated by Django 3.2.19 on 2023-06-05 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NeuralSR_App', '0004_alter_processingimage_sourcefile'),
    ]

    operations = [
        migrations.AddField(
            model_name='processingimage',
            name='radioValue',
            field=models.CharField(default='TestValue', max_length=30),
        ),
        migrations.AlterField(
            model_name='processingimage',
            name='sourceFile',
            field=models.ImageField(upload_to=''),
        ),
    ]
